### ISSUE TITLE
BE: User piggy bank

### ISSUE THREAD

**Issue by jjwyse** [jjwyse/swill#30]
## Outstanding Questions
* Do we immediately create a "piggy" bank entry if the user hits $12.50 for a day?  What if they edit that amount and make it go lower later cause they accidentally entered too high?  Do we then take away their piggy bank?

**Comment by laurawyse** [comment]
I would say yes, we create the piggy bank if they hit $12.50 and if they edit the amount to go lower then we would take it away. 

From Nate: Up to $8 for fitness (every 2 min of cardio = $1; every 2 min of strength = .25 cents).  A person has to make $12.50 for the fitness pig to be earned.  This fitness piggy bank represents $8 to be used on an “off day” of choice.

One more thing to think about: What if they apply there piggy bank for the day and then decide they want to un-do that action? Should we allow that?

**Comment by laurawyse** [comment]
I also wonder if in the UI instead of showing $12.50 we should show $8 +piggy bank or something as it seems confusing to show a higher number than $8 when $8 is really the maximum.
