### ISSUE TITLE
UI: Add scrolling to login screen 

### ISSUE THREAD

**Issue by jjwyse** [jjwyse/swill#83]
## Description
* Greg has an iphone 4 and said he couldn’t see “sign up” link on login screen due to no scrolling.  I don’t like Greg, but nonetheless, we should help out iphone 4 users :)

**Comment by parisroman83** [comment]
Damn Greg and his old tech

**Comment by jjwyse** [comment]
hahaha hey @greglindahl - grow up.

**Comment by greglindahl** [comment]
@jjwyse @parisroman83 you guys need to support OMCs like me.  Plus I'm really hesitating to use this app because I can't have an app icon on my phone.  This is awful - you should just quit and go home.

**Comment by jjwyse** [comment]
[Live look-in of Greg at the game](https://media.giphy.com/media/3oEdv0aZNRcyhPtUXK/giphy.gif) a couple weekends ago.

**Comment by jjwyse** [comment]
[Live look-in of @greglindahl  at the game](https://media.giphy.com/media/3oEdv0aZNRcyhPtUXK/giphy.gif) a couple weekends ago.

cc: @parisroman83

**Comment by parisroman83** [comment]
They are the greatest generation
